# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build the TypeScript code
RUN npm run build

# Expose HTTP port
EXPOSE 8080

# Default command to run the MCP server with HTTP transport
CMD ["node", "dist/index.js", "--transport", "http", "--port", "8080"]
